# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hen/third_party/synergy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hen/third_party/synergy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hen/third_party/synergy/CMakeFiles /Users/hen/third_party/synergy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hen/third_party/synergy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arch

# Build rule for target.
arch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arch
.PHONY : arch

# fast build rule for target.
arch/fast:
	$(MAKE) -f src/lib/arch/CMakeFiles/arch.dir/build.make src/lib/arch/CMakeFiles/arch.dir/build
.PHONY : arch/fast

#=============================================================================
# Target rules for targets named base

# Build rule for target.
base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base
.PHONY : base

# fast build rule for target.
base/fast:
	$(MAKE) -f src/lib/base/CMakeFiles/base.dir/build.make src/lib/base/CMakeFiles/base.dir/build
.PHONY : base/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f src/lib/client/CMakeFiles/client.dir/build.make src/lib/client/CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f src/lib/common/CMakeFiles/common.dir/build.make src/lib/common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named io

# Build rule for target.
io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io
.PHONY : io

# fast build rule for target.
io/fast:
	$(MAKE) -f src/lib/io/CMakeFiles/io.dir/build.make src/lib/io/CMakeFiles/io.dir/build
.PHONY : io/fast

#=============================================================================
# Target rules for targets named ipc

# Build rule for target.
ipc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ipc
.PHONY : ipc

# fast build rule for target.
ipc/fast:
	$(MAKE) -f src/lib/ipc/CMakeFiles/ipc.dir/build.make src/lib/ipc/CMakeFiles/ipc.dir/build
.PHONY : ipc/fast

#=============================================================================
# Target rules for targets named mt

# Build rule for target.
mt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mt
.PHONY : mt

# fast build rule for target.
mt/fast:
	$(MAKE) -f src/lib/mt/CMakeFiles/mt.dir/build.make src/lib/mt/CMakeFiles/mt.dir/build
.PHONY : mt/fast

#=============================================================================
# Target rules for targets named net

# Build rule for target.
net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net
.PHONY : net

# fast build rule for target.
net/fast:
	$(MAKE) -f src/lib/net/CMakeFiles/net.dir/build.make src/lib/net/CMakeFiles/net.dir/build
.PHONY : net/fast

#=============================================================================
# Target rules for targets named platform

# Build rule for target.
platform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 platform
.PHONY : platform

# fast build rule for target.
platform/fast:
	$(MAKE) -f src/lib/platform/CMakeFiles/platform.dir/build.make src/lib/platform/CMakeFiles/platform.dir/build
.PHONY : platform/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f src/lib/server/CMakeFiles/server.dir/build.make src/lib/server/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named synlib

# Build rule for target.
synlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synlib
.PHONY : synlib

# fast build rule for target.
synlib/fast:
	$(MAKE) -f src/lib/synergy/CMakeFiles/synlib.dir/build.make src/lib/synergy/CMakeFiles/synlib.dir/build
.PHONY : synlib/fast

#=============================================================================
# Target rules for targets named shared

# Build rule for target.
shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared
.PHONY : shared

# fast build rule for target.
shared/fast:
	$(MAKE) -f src/lib/shared/CMakeFiles/shared.dir/build.make src/lib/shared/CMakeFiles/shared.dir/build
.PHONY : shared/fast

#=============================================================================
# Target rules for targets named synergyc

# Build rule for target.
synergyc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synergyc
.PHONY : synergyc

# fast build rule for target.
synergyc/fast:
	$(MAKE) -f src/cmd/synergyc/CMakeFiles/synergyc.dir/build.make src/cmd/synergyc/CMakeFiles/synergyc.dir/build
.PHONY : synergyc/fast

#=============================================================================
# Target rules for targets named synergys

# Build rule for target.
synergys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synergys
.PHONY : synergys

# fast build rule for target.
synergys/fast:
	$(MAKE) -f src/cmd/synergys/CMakeFiles/synergys.dir/build.make src/cmd/synergys/CMakeFiles/synergys.dir/build
.PHONY : synergys/fast

#=============================================================================
# Target rules for targets named syntool

# Build rule for target.
syntool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 syntool
.PHONY : syntool

# fast build rule for target.
syntool/fast:
	$(MAKE) -f src/cmd/syntool/CMakeFiles/syntool.dir/build.make src/cmd/syntool/CMakeFiles/syntool.dir/build
.PHONY : syntool/fast

#=============================================================================
# Target rules for targets named synergyd

# Build rule for target.
synergyd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synergyd
.PHONY : synergyd

# fast build rule for target.
synergyd/fast:
	$(MAKE) -f src/cmd/synergyd/CMakeFiles/synergyd.dir/build.make src/cmd/synergyd/CMakeFiles/synergyd.dir/build
.PHONY : synergyd/fast

#=============================================================================
# Target rules for targets named synergy

# Build rule for target.
synergy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synergy
.PHONY : synergy

# fast build rule for target.
synergy/fast:
	$(MAKE) -f src/gui/CMakeFiles/synergy.dir/build.make src/gui/CMakeFiles/synergy.dir/build
.PHONY : synergy/fast

#=============================================================================
# Target rules for targets named synergy_automoc

# Build rule for target.
synergy_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synergy_automoc
.PHONY : synergy_automoc

# fast build rule for target.
synergy_automoc/fast:
	$(MAKE) -f src/gui/CMakeFiles/synergy_automoc.dir/build.make src/gui/CMakeFiles/synergy_automoc.dir/build
.PHONY : synergy_automoc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... arch"
	@echo "... base"
	@echo "... client"
	@echo "... common"
	@echo "... io"
	@echo "... ipc"
	@echo "... mt"
	@echo "... net"
	@echo "... platform"
	@echo "... server"
	@echo "... synlib"
	@echo "... shared"
	@echo "... synergyc"
	@echo "... synergys"
	@echo "... syntool"
	@echo "... synergyd"
	@echo "... synergy"
	@echo "... synergy_automoc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

